In [2]:
#mi primer programa 
nombre = input("Escribe tu nombre: ")
print("Hola " + nombre + ", felicidades haz ingresado correctamente")

Escribe tu nombre: Hirvana J
Hola Hirvana J, felicidades haz ingresado correctamente


In [3]:
#definir mi propia función
def sumar(a, b): 
    return a + b 
sumar(5,4)

9

In [7]:
#realizar operaciones matemáticas
suma = 5 + 9
print("Suma: ",suma)
mult = 7 * 8
print("Multiplicación: ",mult)
exp = 8**3
print("Exponencial",exp)

Suma:  14
Multiplicación:  56
Exponencial 512


In [15]:
#importar librerias como numpy 
import math as m 
a = 90 #valor en radianes
seno = m.sin(a*m.pi/180) #convertir de radianes a grados
print(seno)

1.0


In [28]:
#listas 
list_1 = [0,1,2,3,4,5]
print(list_1)
print(list_1[3])
print(list_1[:4])
list_countries = ['UK', 'USA', 'Mexico', 'Japon', 'China']
print(list_countries)
print(list_countries[0:3])
print(list_countries[1:3])

[0, 1, 2, 3, 4, 5]
3
[0, 1, 2, 3]
['UK', 'USA', 'Mexico', 'Japon', 'China']
['UK', 'USA', 'Mexico']
['USA', 'Mexico']


In [39]:
#diccionarios

dicc = {'nombre': 'Hirvana', 'apellido': 'Juárez', 'edad': '25', 'estado': 'Tlaxcala'}
dicc['nombre']

'Hirvana'

In [15]:
#Arrays 
import numpy as np
arreglo_1 = np.array([[1,2],[3,4]])
print("a=", arreglo_1)

a= [[1 2]
 [3 4]]


In [12]:
a = np.array([1,2,3])
print("a=", a)

a= [1 2 3]


In [14]:
b = np.array([(5,6),(7,8)])
print("b=", b)

b= [[5 6]
 [7 8]]


In [25]:
#operaciones con arreglos
a1 = a + 4
print("a1", a1)
a2 = a * 2
print("a2", a2)
a3 = np.sin(a)
print("a3", a3)

a4 = np.array([[0.5,np.pi],[np.pi/2,np.pi/4]])
print("")
print("a4=",a4)
print("")
a5 = np.sin(a4)
print("a5=",a5)
print("")
a6 = np.log(a4)
print("a6=",a6)

a1 [5 6 7]
a2 [2 4 6]
a3 [0.84147098 0.90929743 0.14112001]

a4= [[0.5        3.14159265]
 [1.57079633 0.78539816]]

a5= [[4.79425539e-01 1.22464680e-16]
 [1.00000000e+00 7.07106781e-01]]

a6= [[-0.69314718  1.14472989]
 [ 0.45158271 -0.24156448]]


In [32]:
c = np.array([1+2j])
print(c*c)

[-3.+4.j]


In [37]:
f = np.zeros([4,4])
print(f)

g = np.ones([3,3])
print(g)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [1]:
import sys