In [2]:
import numpy as np
ej1 = np.arange(12)  #rango del 0-11
print(ej1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
ex2 = np.arange(1,10)  #rango que comienza del 1-9
print(ex2)

[1 2 3 4 5 6 7 8 9]


In [20]:
ex3 = np.arange(0,25,2.5)   #rango que comienza del 0 y termina antes de 25, con un esparciamiento de 2.5 en 2.5
print(ex3)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [19]:
ex4 = np.linspace(0,25,10)   #rango que comienza del 0-25 y el 3er parametro muestra los números 
print(ex4)
#linspace, (inicial, final, numvalores)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [39]:
ex5 = np.arange(0,20).reshape(5,4)   #reshape se utliza para crear matrices en 2D (ren,col)
print(ex5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [46]:
a = np.array([1,2,3,4,5])
print(a)
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())

[1 2 3 4 5]
15
1
5
3.0


In [55]:
b = np.random.random((3,2))
print(b)
print("")
c = np.random.random((4,2)).reshape(4,2)
print(c)

[[0.06850777 0.58292155]
 [0.71978931 0.47080913]
 [0.08720339 0.05246016]]

[[0.18287331 0.9681119 ]
 [0.66420119 0.38780769]
 [0.73896727 0.52883494]
 [0.21070317 0.18799622]]


In [7]:
an = np.array([1,2,3,4])
an[1:-1]
an [::2]

array([1, 3])

In [9]:
an.dtype

dtype('int32')

In [10]:
type(an)

numpy.ndarray

## DIMENSIONS AND SHAPES

In [12]:
B = np.array([[1,2,3],
             [4,5,6]])

In [13]:
B.shape

(2, 3)

In [14]:
B.ndim

2

In [15]:
B.size

6

In [16]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

In [17]:
print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [19]:
j = np.arange(5)
j + 20

array([20, 21, 22, 23, 24])

In [20]:
j*10

array([ 0, 10, 20, 30, 40])

In [23]:
j.sum(axis=0)

10

In [27]:
B.sum(axis=1)

array([ 6, 15])

## BOOLEAN ARRAYS

In [31]:
a = np.arange(4)

In [32]:
a

array([0, 1, 2, 3])

In [33]:
a[[0,-1]]

array([0, 3])

In [34]:
a[0:-1]

array([0, 1, 2])

In [35]:
a[[True, False, False, True]]

array([0, 3])

In [36]:
a >= 2

array([False, False,  True,  True])